server:
  port: 7777
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/benkyoukai?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: username # username
    password: password # password
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

file-save-path: D:\code\Project\SotsuGyou\uploads\

avatar-path: D:\code\Project\SotsuGyou\uploads\avatar\

kaiwa-path: D:\code\Project\SotsuGyou\kaiwa\
